[박세익][ADD] 제품 카테고리별 상품 정보 API
wecode-bootcamp-korea/44-1st-6ixSense-backend pull request #5
Opened 2023-04-05 02:29 UTC by Parkseyik

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 제품리스트 페이지에서 카테고리를 나누어 필터링 작업을 구현하였습니다.

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 제품리스트 페이지에서 제품 카테고리별로 상품 정보에 대한 api 보내주기를 구현
- Dao.js에서 "catergories.id" 와 "products.category_id"를 JOIN 한 후,
- "products.id" 와 "product_images.product_id"를 JOIN 하였습니다. 

<br />

## :: 테스트 결과 이미지

<img width="711" alt="스크린샷 2023-04-05 오전 11 12 34" src="https://user-images.githubusercontent.com/124123399/229965763-14ae6869-8ab5-48ab-a618-eb99700810bb.png">

<br />

2023-04-05 02:41 UTC, Kang-kyunghun reviewed
1. 필터링 요소가 카테고리 밖에 없나요?(혹시 다른게 있나 해서요.)
2. 정렬, 페이지네이션도 추가해 주세요.

2023-04-05 02:41 UTC, Kang-kyunghun commented on controllers/productController.js
> +  const { categoriesId } = req.query;
```suggestion
  const { categoryId } = req.query;
```

2023-04-05 02:51 UTC, Parkseyik commented on controllers/productController.js
> +  const { categoriesId } = req.query;
필터링 요소는 낮은가격순, 높은가격순도 추가 예정입니다.

2023-04-05 08:36 UTC, Kang-kyunghun commented
정렬하고 페이지네이션 추가가 안 되어 있네요! 추가해 주시고 라벨 변경해 주세요.

2023-04-10 07:07 UTC, Kang-kyunghun requested changes

2023-04-10 07:07 UTC, Kang-kyunghun commented on models/productDao.js
> +const productList = async (categoryId, sort, limit, offset) => {
```suggestion
const getProductList = async (categoryId, sort, limit, offset) => {
```

2023-04-10 07:07 UTC, Kang-kyunghun commented on routes/productRouter.js
> +router.get('/productlist', productController.productList);
```suggestion
router.get('', productController.productList);
```

2023-04-10 07:07 UTC, Kang-kyunghun commented on services/productService.js
> +const productList = async (categoryId, sort, limit, offset) => {
```suggestion
const getProductList = async (categoryId, sort, limit, offset) => {
```

2023-04-10 07:07 UTC, Kang-kyunghun commented on controllers/productController.js
> +const productList = catchAsync(async (req, res) => {
```suggestion
const getProductList = catchAsync(async (req, res) => {
```

2023-04-10 10:56 UTC, merged