feature/detail-page-product-like 기능 추가
wecode-bootcamp-korea/44-1st-6ixSense-backend pull request #6
Opened 2023-04-05 02:55 UTC by songsong95

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

file:///home/song137/%EC%82%AC%EC%A7%84/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7/6ixSence%20%EC%A2%8B%EC%95%84%EC%9A%94%20%EA%B8%B0%EB%8A%A5.png

file:///home/song137/%EC%82%AC%EC%A7%84/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7/6ixSence%20%EC%83%81%ED%92%88%20%ED%8E%98%EC%9D%B4%EC%A7%80%20%ED%95%A0%EC%9D%B8%EC%9C%A8%20%EC%A0%81%EC%9A%A9.png

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-04-05 08:41 UTC, Kang-kyunghun requested changes

2023-04-05 08:41 UTC, Kang-kyunghun commented on controllers/detailPageController.js
> +  console.log(productId);
console.log 지워주세요.

2023-04-05 08:41 UTC, Kang-kyunghun commented on controllers/detailPageController.js
> +  const detailProduct = await detailPageService.getProduct(productId);
1. 변수명은 명사로 지어주는데, 중점이 되는 속성을 먼저 그리고 부수적인 속성을 나중에 적어주는 것이 더 자연스럽습니다.
ex) productDetail, productList
2. 백엔드는 page가 아닌 데이터를 중심으로 코드를 진행 합니다. 서비스 이름에서 page를 제거하고 다음과 같이 작성해 주세요.
```suggestion
  const productDetail = await productService.getProduct(productId);
```

2023-04-05 08:41 UTC, Kang-kyunghun commented on db/migrations/20230404061219_create_users_table.sql
> +  phone_number VARCHAR(30) NOT NULL,
원종님 PR에서도 봤던 코드 갔던데 두 분이서 공통된 수정 사항이 있는걸까요?
그렇다면 원종님 코드가 merge 되어 main이 업데이트 되었으니 해당 PR도 업데이트 해주세요.

2023-04-05 08:41 UTC, Kang-kyunghun commented on routers/index.js
> +const express = require('express');
LIKE 또한 하나의 기능입니다. 해당 브렌치에서 분리 한 뒤에 따로 PR 남겨주세요.

2023-04-06 01:28 UTC, Kang-kyunghun requested changes

2023-04-06 01:28 UTC, Kang-kyunghun commented on models/detailPageDao.js
> +            products.name,
데이터를 전달 할 때, PK도 같이 보내주는 것이 좋습니다.
해당 PK는 다른 AP를 이용할 때 활용 될 수 있습니다.
예를 들어 좋아요 기능을 할 때 productId와 userId가 필요할텐데, 그 때 productId를 알려면 미리 프론트엔드에서 productId를 알고 있어여 하고, 따라서 상세 정보를 주는 API에서 productId를 전달 해줬어야 합니다.
```suggestion
      `SELECT
            products.id, 
            products.name,
```

2023-04-06 03:07 UTC, songsong95 commented
![스크린샷 2023-04-06 12-05-26](https://user-images.githubusercontent.com/120084509/230262365-bba3635c-0c3f-4ce3-be49-1838b56bcf45.png)

2023-04-06 05:23 UTC, merged