[44기 김원종][ADD] Authentication 기능추가
wecode-bootcamp-korea/44-1st-6ixSense-backend pull request #8
Opened 2023-04-05 07:50 UTC by thornewater

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- jwt를 사용하여 토큰 확인

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- jwt를 사용하여 할당된 토큰이 정상적인 토큰인지 확인

<br />

## :: 테스트 결과 이미지

<br />

## :: 기타 질문 및 특이 사항

2023-04-06 03:00 UTC, Kang-kyunghun requested changes

2023-04-06 03:00 UTC, Kang-kyunghun commented on app.js
> +const router = require('./routes/index');
```suggestion
const router = require('./routes');
```

2023-04-06 03:00 UTC, Kang-kyunghun commented on middleware/auth.js
> +    req.user = await decoded.id;
```suggestion
    req.userId = await decoded.id;
```

2023-04-06 03:00 UTC, Kang-kyunghun commented on middleware/auth.js
> +    return res.status(403).json({
```suggestion
    return res.status(401).json({
```

2023-04-07 02:03 UTC, Kang-kyunghun requested changes

2023-04-07 02:03 UTC, Kang-kyunghun commented on middleware/auth.js
> +    req.userId = await decoded.id;
user 확인 로직을 추가 하셨네요? 그렇다면 req.userId가 아닌 req.user로 바껴야 하게죠? 수정해 주세요.
```suggestion
    req.user = user;
```

2023-04-07 03:05 UTC, thornewater commented
회원가입기능까지 추가하였습니다.

2023-04-07 03:21 UTC, merged