[44기][송석준][ADD] 좋아요 기능 추가
wecode-bootcamp-korea/44-1st-6ixSense-backend pull request #9
Opened 2023-04-05 09:30 UTC by songsong95

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성

좋아요 추가 and 삭제 기능 구현

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

file:///home/song137/%EC%82%AC%EC%A7%84/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202023-04-06%2016-12-09.png

file:///home/song137/%EC%82%AC%EC%A7%84/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202023-04-06%2016-12-37.png

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-04-06 01:32 UTC, Kang-kyunghun commented
PR template 작성 해주세요.

2023-04-06 07:30 UTC, songsong95 commented
![스크린샷 2023-04-06 16-12-09](https://user-images.githubusercontent.com/120084509/230305944-bb8f83c0-83d6-489e-977c-53390f5cb5fb.png)

![스크린샷 2023-04-06 16-12-37](https://user-images.githubusercontent.com/120084509/230305999-d52e1f95-430f-467b-be74-399d0cb5c22e.png)

2023-04-07 02:06 UTC, Kang-kyunghun requested changes

2023-04-07 02:06 UTC, Kang-kyunghun commented on controllers/likeController.js
> +const likes = catchAsync(async (req, res) => {
```suggestion
const createLike = catchAsync(async (req, res) => {
```

2023-04-07 02:06 UTC, Kang-kyunghun commented on controllers/likeController.js
> +const likesCensel = catchAsync(async (req, res) => {
함수명은 행위를 나타낼 수 있게 동사형으로 지어주면 좋습니다.
```suggestion
const deleteLike = catchAsync(async (req, res) => {
```

2023-04-07 02:06 UTC, Kang-kyunghun commented on routes/likeRouter.js
> +router.delete('/:userId', likeController.likesCensel);
userId는 토큰을 확인하여 user를 확인하는 미들웨어를 통해서 받아주세요.
해당 부분은 현재 작업 중인 담당자와 상의해 주세요.

2023-04-07 02:06 UTC, Kang-kyunghun commented on services/likeService.js
> +const likes = async (userId, productId) => {
```suggestion
const createLike = async (userId, productId) => {
```

2023-04-07 02:06 UTC, Kang-kyunghun commented on services/likeService.js
> +const likesCensel = async (userId) => {
```suggestion
const deleteLike = async (userId) => {
```

2023-04-07 02:23 UTC, songsong95 commented on routes/likeRouter.js
> +router.delete('/:userId', likeController.likesCensel);
토큰 부분은 담당자분 작업이 완료되는대로 추가하겠습니다!

2023-04-07 07:00 UTC, Kang-kyunghun requested changes

2023-04-07 07:00 UTC, Kang-kyunghun commented on services/likeService.js
> +};
좋아요 생성 전에 productId가 존재하는지에 대한 판단 여부 로직 추가해 주세요.

2023-04-10 00:52 UTC, Kang-kyunghun requested changes

2023-04-10 00:52 UTC, Kang-kyunghun commented on routes/index.js
> +router.use('/detailpage', productRouter.router);
```suggestion
router.use('products', productRouter.router);
```

2023-04-10 00:52 UTC, Kang-kyunghun commented on controllers/productController.js
> +  return res.status(200).json(productDetail);
객체를 제거한 이유가 있을까요??
이렇게 보내면 key가 없는 상태로 배열이 전송 될 것 같은데, 
데이터를 보낼 때는 key 같이 보내서 데이터를 특정 지을 수 있게 해주는 것이 좋습니다. 
다시 추가해 주세요.
```suggestion
  return res.status(200).json({productDetail});
```

2023-04-10 01:35 UTC, merged